version: '3.4'

services:
  parsedmarc:
    container_name: "parsedmarc"
    build:
      context: .
      dockerfile: parsedmarc/Dockerfile
    command: "parsedmarc -c /etc/parsedmarc.ini"
    tty: true
    volumes:
      - ./parsedmarc/parsedmarc.ini:/etc/parsedmarc.ini:z
      #- /path/to/GeoIP:/usr/share/GeoIP
    restart: unless-stopped
    networks:
      - parsedmarc-network
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    container_name: "elasticsearch"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - cluster.name=parsedmarc
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data/
    restart: "unless-stopped"
    networks:
      - parsedmarc-network
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

  kibana:
    container_name: "kibana"
    image: docker.elastic.co/kibana/kibana:7.17.0
    environment:
      - server.name=parsedmarc
      - server.host="0"
      - elasticsearch.hosts=http://elasticsearch:9200
      - xpack.monitoring.ui.container.elasticsearch.enabled=true
    ports:
      - "5601:5601"
    restart: unless-stopped
    networks:
      - parsedmarc-network
    depends_on:
      elasticsearch:
        condition: service_healthy

  nginx:
    container_name: "nginx"
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:z
      - ./nginx/ssl/:/etc/nginx/ssl/:z
      - nginx_secrets:/etc/nginx-secrets
    networks:
      - parsedmarc-network

networks:
    parsedmarc-network:
      driver: bridge
volumes:
  elasticsearch_data:
  nginx_secrets:
