version: '3.4'

services:
  parsedmarc:
    container_name: "parsedmarc"
    build:
      context: ./parsedmarc/
      dockerfile: ./Dockerfile
    tty: true
    volumes: []
      #- /path/to/GeoIP:/usr/share/GeoIP
    environment:
      # in general: <section>.<option>
      parsedmarc.general.save_aggregate: "True"
      parsedmarc.general.save_forensic: "True"
      # parsedmarc.mailbox.watch: "True"
      # parsedmarc.imap.host: "imap.example.com"
      # parsedmarc.imap.user: "parsedmarc@example.com"
      # parsedmarc.imap.password: "somepassword"
      parsedmarc.elasticsearch.hosts: "http://elasticsearch:9200"
      parsedmarc.elasticsearch.ssl: "False"
    restart: unless-stopped
    networks:
      - parsedmarc-network
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: "elasticsearch"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - cluster.name=parsedmarc
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data/:/usr/share/elasticsearch/data/:z
    restart: "unless-stopped"
    networks:
      - parsedmarc-network
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

  kibana:
    container_name: "kibana"
    image: docker.elastic.co/kibana/kibana:7.17.0
    environment:
      SERVER_NAME: parsedmarc
      SERVER_HOST: "0.0.0.0"
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: "true"
    restart: unless-stopped
    networks:
      - parsedmarc-network
    depends_on:
      - elasticsearch

  nginx:
    container_name: "nginx"
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:z
      - ./nginx/ssl/:/etc/nginx/ssl/:z
      - ./nginx/htpasswd:/etc/nginx/htpasswd:z
    networks:
      - parsedmarc-network

networks:
    parsedmarc-network:
      driver: bridge
